# -*- coding: utf-8 -*-
"""translate_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nblnoaLP7xcjFPLPlv14wAAqtTipID3
"""

!pip install streamlit
!pip install streamlit gTTS googletrans==4.0.0-rc1

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

! wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501



